### ISSUE TITLE
Any notes on `sdl_gamepad`? 

### ISSUE THREAD

**Issue by Levi-Lesches** [sansuido/sdl3#2]
Hi again, not really an issue, more of an open-ended question/discussion. Thanks to this package I was able to publish [`sdl_gamepad`](https://pub.dev/packages/sdl_gamepad), a Dart API that tries to hide the FFI details and focus more on the gamepad side. Don't worry -- I credited you on the README. It's not totally complete, like it doesn't have all the mappings, but I made it practically overnight and it fits my team's needs for now. I think I'm going to release another package, `sdl_gamepad_flutter`, that will handle the native build process until Native Assets are released. 

Just wanted to know your thoughts and any advice specifically relating to SDL itself. For example, I had trouble getting the Dart event loop to properly end, which was blocking CTRL+C and Flutter's hot reload, and it turned out I wasn't handling SDL quit events. Feel free to close this as well since again, not really an issue. 

Thanks again!

**Comment by sansuido** [comment]
Thank you for creating and publishing the gamepad library! My home-made program focuses on mice, and I'm not familiar with gamepads, so this will be helpful.
I'm not familiar with flutter either, so I can't comment on the glitches in hot reload behavior. However, I have confirmed that it is not compatible with dart's isolate unless the loop processing is improved.
thank you!
